## 00. PyTorch Fundamentals 

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


In [3]:
scalar = torch.tensor(7)
scalar 



tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vectorabs 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
# TENSOR

TENSOR = torch.tensor([[[[6, 3, 3],
                        [5, 4, 96],
                        [7, 11, 49],
                       [1003, 492, 59]]]])

TENSOR

tensor([[[[   6,    3,    3],
          [   5,    4,   96],
          [   7,   11,   49],
          [1003,  492,   59]]]])

In [18]:
TENSOR.ndim

4

In [19]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [20]:
TENSOR[0]

tensor([[[   6,    3,    3],
         [   5,    4,   96],
         [   7,   11,   49],
         [1003,  492,   59]]])

In [21]:
### Random tensors

In [22]:
random_tensor = torch.rand(1 , 10, 10)
random_tensor

tensor([[[2.9681e-01, 3.7824e-01, 7.5060e-01, 5.7776e-01, 5.9049e-01,
          2.1011e-01, 1.8256e-01, 2.9057e-01, 5.0011e-01, 5.7068e-01],
         [6.6356e-01, 7.8993e-01, 5.3615e-01, 9.0346e-01, 6.1158e-01,
          7.7530e-01, 4.8892e-01, 7.3568e-01, 2.8882e-01, 4.2269e-01],
         [4.2472e-01, 8.1007e-01, 4.7226e-01, 7.8306e-01, 1.2285e-01,
          5.1320e-01, 8.4120e-01, 3.0620e-01, 1.0303e-01, 1.9127e-01],
         [7.2199e-02, 9.9753e-01, 1.9257e-01, 3.8502e-01, 1.0987e-01,
          1.6107e-01, 3.7690e-01, 9.1022e-01, 5.6416e-01, 4.9653e-01],
         [4.9561e-01, 4.1542e-01, 8.3423e-01, 7.7342e-01, 3.3393e-01,
          6.4293e-01, 6.3592e-01, 4.7459e-01, 7.4879e-01, 1.0255e-01],
         [5.2373e-02, 9.3823e-01, 7.5289e-01, 3.0990e-01, 3.1183e-01,
          3.2895e-01, 5.5233e-01, 2.6611e-01, 3.6898e-01, 4.9263e-01],
         [9.6727e-01, 6.1808e-01, 5.7834e-01, 2.8392e-01, 4.0646e-01,
          5.3517e-01, 5.6876e-01, 5.6903e-01, 1.9537e-01, 9.8558e-01],
         [8.2

In [23]:
random_tensor.ndim

3

In [24]:
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # Height, width, colour channels (R, G, B)%%!
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
random_tensor = torch.rand(1, 10, 10)
random_tensor 


tensor([[[0.0283, 0.8913, 0.2570, 0.4253, 0.8359, 0.1204, 0.1688, 0.2192,
          0.4436, 0.6620],
         [0.2011, 0.8951, 0.2580, 0.8230, 0.7577, 0.9454, 0.3903, 0.6840,
          0.7803, 0.4868],
         [0.0574, 0.9177, 0.0100, 0.8998, 0.5050, 0.8076, 0.0488, 0.9037,
          0.5269, 0.5770],
         [0.0598, 0.4467, 0.4383, 0.9397, 0.7382, 0.9481, 0.6007, 0.5981,
          0.3437, 0.5601],
         [0.2312, 0.7702, 0.1370, 0.8892, 0.5327, 0.4009, 0.0293, 0.1850,
          0.8922, 0.4495],
         [0.7057, 0.1056, 0.4558, 0.1202, 0.6987, 0.9857, 0.6139, 0.3284,
          0.9797, 0.9750],
         [0.7861, 0.9597, 0.8922, 0.5056, 0.5567, 0.4197, 0.3814, 0.7770,
          0.5592, 0.4672],
         [0.9870, 0.7346, 0.1363, 0.3478, 0.5815, 0.5246, 0.7284, 0.4804,
          0.8864, 0.9251],
         [0.9344, 0.3167, 0.0414, 0.0117, 0.2642, 0.3702, 0.9969, 0.7264,
          0.0784, 0.4760],
         [0.0142, 0.0694, 0.8119, 0.8908, 0.5069, 0.3738, 0.3952, 0.1170,
          0.0763,

In [26]:
random_tensor

tensor([[[0.0283, 0.8913, 0.2570, 0.4253, 0.8359, 0.1204, 0.1688, 0.2192,
          0.4436, 0.6620],
         [0.2011, 0.8951, 0.2580, 0.8230, 0.7577, 0.9454, 0.3903, 0.6840,
          0.7803, 0.4868],
         [0.0574, 0.9177, 0.0100, 0.8998, 0.5050, 0.8076, 0.0488, 0.9037,
          0.5269, 0.5770],
         [0.0598, 0.4467, 0.4383, 0.9397, 0.7382, 0.9481, 0.6007, 0.5981,
          0.3437, 0.5601],
         [0.2312, 0.7702, 0.1370, 0.8892, 0.5327, 0.4009, 0.0293, 0.1850,
          0.8922, 0.4495],
         [0.7057, 0.1056, 0.4558, 0.1202, 0.6987, 0.9857, 0.6139, 0.3284,
          0.9797, 0.9750],
         [0.7861, 0.9597, 0.8922, 0.5056, 0.5567, 0.4197, 0.3814, 0.7770,
          0.5592, 0.4672],
         [0.9870, 0.7346, 0.1363, 0.3478, 0.5815, 0.5246, 0.7284, 0.4804,
          0.8864, 0.9251],
         [0.9344, 0.3167, 0.0414, 0.0117, 0.2642, 0.3702, 0.9969, 0.7264,
          0.0784, 0.4760],
         [0.0142, 0.0694, 0.8119, 0.8908, 0.5069, 0.3738, 0.3952, 0.1170,
          0.0763,

In [27]:
torch.rand(size = (3, 3))

tensor([[0.8304, 0.5296, 0.9672],
        [0.7454, 0.9256, 0.9117],
        [0.9976, 0.9901, 0.2885]])

In [28]:
ones = torch.ones(size = (7, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [29]:
zeros = torch.zeros(size = (35, 3))

In [30]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
ones.dtype

torch.float32

In [32]:
random_tensor.dtype

torch.float32

In [33]:
### Range of tensors & tensors-like

In [34]:
torch.range(0, 10)

C:\Users\Smoke Nandos\AppData\Local\Temp\ipykernel_20196\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
one_to_ten = torch.arange (start = 0, end = 1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [36]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                              device = None,
                              requires_grad = False)


In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [40]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [41]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [42]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6535, 0.5993, 0.5420, 0.8875],
        [0.8758, 0.3405, 0.7447, 0.7959],
        [0.6147, 0.6170, 0.3181, 0.3504]])

In [43]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [44]:
some_tensor.size()

torch.Size([3, 4])

In [45]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} ")
print(f"Shape of tensor: {some_tensor.shape} ")
print(f"Device tensor is on: {some_tensor.device} ")

tensor([[0.6535, 0.5993, 0.5420, 0.8875],
        [0.8758, 0.3405, 0.7447, 0.7959],
        [0.6147, 0.6170, 0.3181, 0.3504]])
Datatype of tensor: torch.float32 
Shape of tensor: torch.Size([3, 4]) 
Device tensor is on: cpu 


In [46]:
some_tensor = torch.rand(9, 4)
some_tensor

tensor([[0.6834, 0.9969, 0.2182, 0.3256],
        [0.9931, 0.3808, 0.6323, 0.7828],
        [0.1824, 0.3304, 0.3675, 0.8745],
        [0.5394, 0.3127, 0.6729, 0.3118],
        [0.3314, 0.3245, 0.4428, 0.6239],
        [0.1731, 0.8277, 0.5208, 0.6195],
        [0.0955, 0.5514, 0.8513, 0.9578],
        [0.6391, 0.6115, 0.6305, 0.8120],
        [0.5186, 0.2336, 0.4066, 0.6900]])

In [47]:
some_tensor = some_tensor.to(torch.float16)

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} ")


tensor([[0.6836, 0.9971, 0.2183, 0.3257],
        [0.9932, 0.3809, 0.6323, 0.7827],
        [0.1824, 0.3303, 0.3674, 0.8745],
        [0.5396, 0.3127, 0.6729, 0.3118],
        [0.3313, 0.3245, 0.4429, 0.6240],
        [0.1731, 0.8276, 0.5210, 0.6196],
        [0.0955, 0.5513, 0.8511, 0.9580],
        [0.6392, 0.6113, 0.6304, 0.8120],
        [0.5186, 0.2335, 0.4065, 0.6899]], dtype=torch.float16)
Datatype of tensor: torch.float16 


In [48]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
some_tensor = some_tensor.to(device)

print(f"Device tensor is on:", some_tensor.device)

Device tensor is on: cpu


In [49]:
#### Manipulating Tensors

In [50]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [51]:
tensor = tensor * 10


In [52]:
tensor

tensor([10, 20, 30])

In [53]:
tensor - 10

tensor([ 0, 10, 20])

In [54]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [55]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [56]:
### Matrix multiplication (dot product)



In [57]:
tensor

tensor([10, 20, 30])

In [58]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [59]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor} " )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9]) 


In [60]:
torch.matmul(tensor, tensor)


tensor(14)

In [61]:
tensor

tensor([1, 2, 3])

In [62]:
1*1 + 2 * 2 + 3 * 3 

14

In [63]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 996 μs


In [64]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [65]:
import time
import torch

tensor = torch.randn(3,3)

start = time.perf_counter()
result = torch.matmul(tensor, tensor)
end = time.perf_counter()

print("Execution time (CPU):", (end - start) * 1e6, "microseconds")

Execution time (CPU): 3239.0999840572476 microseconds


In [66]:
tensor @ tensor

tensor([[ 0.3716, -0.3445,  0.5255],
        [ 0.2804, -0.7271, -0.0085],
        [ 0.7374, -0.1295, -0.1837]])

In [67]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [68]:
### Inner dimensions must match.

In [69]:
### Matrix Multiplication Shapes

In [70]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) #torch.mm = torch.matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [71]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [73]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [75]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} < - inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")





Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) < - inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [76]:
###Tensor aggregation

In [78]:
x = torch.arange(1 ,100, 10)

x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [80]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [82]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [84]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [85]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [86]:
torch.argmin(x)

tensor(0)

In [88]:
torch.argmax(x)

tensor(9)

In [89]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [90]:
x.argmin()

tensor(0)

In [94]:
[0]

[0]

In [95]:
x.argmax()

tensor(9)

In [98]:
x[9]

tensor(91)

In [99]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [101]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [103]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [106]:
x_stacked = torch.stack([x, x, x, x], dim = -1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [107]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [108]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [111]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [112]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [113]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [115]:
print(f"Previous tensor: {x_reshaped} ")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [118]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [119]:
x_reshaped.shape

torch.Size([1, 9])

In [120]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [123]:
x_reshaped.squeeze().shape

torch.Size([9])

In [124]:
x_original = torch.rand(size = (224, 224, 3)) #Height, width, colour_channels

x_permuted = x_original.permute(2, 0, 1) # shift axis 0 to 1, 1 to 2, 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [126]:
x_original[0, 0, 0] = 728242

In [127]:
x_permuted

tensor([[[7.2824e+05, 3.3725e-01, 1.0604e-01,  ..., 4.0825e-01,
          2.0156e-01, 5.1031e-01],
         [9.7186e-01, 7.8833e-01, 3.6808e-01,  ..., 1.8693e-01,
          1.7919e-01, 5.0065e-01],
         [3.6313e-01, 5.4469e-02, 8.2807e-02,  ..., 2.0431e-02,
          8.6299e-02, 9.5816e-01],
         ...,
         [3.3934e-01, 6.9910e-01, 8.9543e-01,  ..., 2.7282e-01,
          7.2637e-01, 4.9254e-01],
         [8.3189e-01, 9.0440e-01, 6.5437e-01,  ..., 3.5149e-01,
          3.4256e-01, 4.6439e-01],
         [5.9765e-01, 6.6114e-01, 5.3577e-01,  ..., 1.0783e-01,
          1.6757e-01, 2.8521e-01]],

        [[4.8823e-01, 9.5929e-01, 5.1042e-01,  ..., 2.8372e-01,
          9.2941e-01, 2.5464e-01],
         [8.4985e-01, 4.0561e-01, 8.1766e-01,  ..., 7.8508e-01,
          3.7153e-01, 4.6263e-01],
         [6.8227e-01, 7.3577e-01, 9.6593e-01,  ..., 2.0839e-02,
          2.7630e-01, 9.1188e-01],
         ...,
         [4.2911e-01, 8.7075e-01, 5.4287e-01,  ..., 8.2378e-02,
          8.079

In [128]:
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(728242.), tensor(728242.))

In [130]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [132]:
print(tensor, tensor.shape)

tensor([[ 0.8954, -0.5974,  0.0843],
        [ 0.7623, -0.2515, -0.7031],
        [ 0.2994,  0.4764,  0.3550]]) torch.Size([3, 3])


In [133]:
tensor = torch.tensor ([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print(tensor, tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [135]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [137]:
x[0, 0]

tensor([1, 2, 3])

In [138]:
x[0][1][1]

tensor(5)

In [141]:
x[:, 0] ## : - Select all of a target dimension

tensor([[1, 2, 3]])

In [143]:
# All values of 0th & 1st dimensions. Only index 1 of 2nd dimensions

x[:, :, 2]

tensor([[3, 6, 9]])

In [144]:
# All values of 0 dimension but only 1 index value of 1st & 2nd dimensions

x[:, 1, 1]

tensor([5])

In [145]:
# Index 0 of 0th and 1st dimension & all values of 2nd dimension

x[0, 0, :]

tensor([1, 2, 3])

In [146]:
# Index on x to return 9

x[0, 2, 2]

tensor(9)

In [149]:
# Index on x to return 3, 6, 9

x[:, :, 2]

tensor([[3, 6, 9]])

In [150]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [153]:
#PyTorch tensors & NumPy

In [155]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #When conv from numpy to pytorch, pytorch reflects numpy's default datatype o/ float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [156]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [157]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor




(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [159]:
tensor = tensor + 1
tensor, numpy_tensor 

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [160]:
import numpy as np 
import math

#Create random input & output dataabs

x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6 #10^6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3


    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)


    # Back prop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()


    #Update weights 

    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d 

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')
    


99 1978.615654166329
199 1314.348815020468
299 874.2247559276974
399 582.5715178754701
499 389.2762272903871
599 261.1486479043071
699 176.2041617612432
799 119.87885149659151
899 82.52351165718048
999 57.744290910919986
1099 41.303833430892205
1199 30.39352057268499
1299 23.151435355676185
1399 18.34304660055681
1499 15.149658052144511
1599 13.028234998799572
1699 11.618512691308863
1799 10.681428889387252
1899 10.058311264702526
1999 9.643818515779083
Result: y = 0.010078226899916231 + 0.8303688579157544 x + -0.0017386618426550413 x^2 + -0.0895792038011363 x^3


In [162]:
## Reproducability (trying to take the random out of random)

In [164]:
torch.rand(3, 3)

tensor([[0.0315, 0.1807, 0.0103],
        [0.7322, 0.0879, 0.5684],
        [0.1521, 0.9822, 0.3392]])

In [165]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6838, 0.5655, 0.7985, 0.9117],
        [0.4717, 0.9577, 0.9576, 0.2834],
        [0.4967, 0.7428, 0.3855, 0.7848]])
tensor([[0.6514, 0.5152, 0.2990, 0.1312],
        [0.3004, 0.0437, 0.9555, 0.3806],
        [0.3598, 0.1479, 0.0961, 0.6623]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [167]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4) 

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [205]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device 

'cpu'

In [ ]:
tensor = torch.tensor([1, 2, 3], device = "cpu